apiVersion: apps/v1
kind: Deployment
metadata:
  name: age-calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: age-calculator
  template:
    metadata:
      labels:
        app: age-calculator
    spec:
      containers:
      - name: age-calculator
        image: syedsohail746/age-calculator:1
        ports:
        - containerPort: 80  # ✅ Your container port

