apiVersion: v1
kind: Service
metadata:
  name: age-calculator-service
spec:
  selector:
    app: age-calculator
  ports:
    - protocol: TCP
      port: 86         # Exposed service port
      targetPort: 86   # Container port inside the pod
  type: NodePort       # Or LoadBalancer for cloud

